allowBuilds:
  sharp: true
  unrs-resolver: true

supportedArchitectures:
  os:
    - current
    - linux
  cpu:
    - current
    - x64
  libc:
    - current
    - glibc

overrides:
  postcss: 8.5.10
